language: node_js
node_js:
- '16'
addons:
  apt:
    packages:
      - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
script:
- npm run all
deploy:
  provider: npm
  skip_cleanup: true
  email: jnbdzjnbdz@gmail.com
  api_key:
    secure: 
  on:
    tags: true
    branch: master